name: 'WIPAC Dev Mypy'
description: 'GitHub Action Package for Running Mypy'

# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - run: pip install --upgrade pip
      shell: bash
    - run: pip install mypy
      shell: bash
    - name: Pip Install Local Package and All 'requirements*.txt' Files We Find
      run: |
        ([ -e "setup.py" ] && pip install .) || (echo "no setup.py")
        # ex: pip install -r requirements.txt requirements-dev.txt foo/requirements.txt
        (pip install `find . -name 'requirements*.txt' | rev | sed -z 's/\n/ r- /g' | rev`) || (echo "no requirements*.txt files")
      shell: bash
    - name: Run Mypy (and Try to Install Type-Packages)
      run: |
        flags="--namespace-packages --exclude build/"
        it_flags="--install-types --non-interactive"
        (mypy $it_flags $flags . 2>/dev/null) || (echo "no type-packages to install" && mypy $flags .)
      shell: bash